prompts:
  general:
    - "Quels sont les principaux défis auxquels les agriculteurs sont confrontés aujourd'hui ?"
    - "Explique-moi les différences entre l'agriculture biologique et l'agriculture conventionnelle."
    - "Comment l'agriculture contribue-t-elle à la lutte contre le changement climatique ?"
    - "Quels sont les avantages et inconvénients des OGM dans l'agriculture ?"

  techniques:
    - "Comment fonctionne la rotation des cultures et pourquoi est-elle importante ?"
    - "Explique les avantages de l'irrigation goutte à goutte pour les cultures."
    - "Quels sont les types de fertilisants les plus utilisés en agriculture et leurs impacts ?"
    - "Quelles sont les techniques de lutte biologique contre les nuisibles ?"

variables:
  - label : Région viticole
    nature: 'radio'
    key : param1
    options : ["Champagne", "Vin de bordeaux", "Occitanie"]
    value :
  - label : Millésime
    nature: 'selectbox'
    key : param2
    options : ["2019", "2020", "2021"]
    value :
  - label : Indicateur
    nature: 'multiselect'
    key : param3
    options : ["Prix de revient par hectare (€/ha)", "Prix de revient par hectolitre (€/hl)", "Coût de la main d’oeuvre par hectare (€/ha)", "Frais d’habillage ou de mise (€/bouteille)"]
    value :

prompt_system: "Prompt system par défaut"

prompt_template: "
Paramètre 1 : {param1}
Paramètre 2 : {param2}
Paramètre 3 : {param3}

Documents partagées : {commonContext}
Document de référence : {documentContext}

{prompt_system}

Voici l'historique des messages : {messages}
Les attentes de l'utilisateur sont : {query}
"